/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ServerOptions {
  host?: string
  port: number
  maxHops?: number
  perTtlTimeoutMs?: number
  ifaceHint?: string
  middleware?: (...args: any[]) => any
}
export declare function startServer(opts: ServerOptions): Server
export declare class Server {
  /**
   * Start the server and block until it's stopped
   * This method never returns unless the server is stopped via stop()
   */
  start(): void
  /** Stop the server */
  stop(): void
  /** Register event listener */
  on(event: string, cb: (...args: any[]) => any): void
}
