/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ServerOptions {
  host?: string
  port: number
  maxHops?: number
  perTtlTimeoutMs?: number
  ifaceHint?: string
}
export declare function startServer(opts: ServerOptions): ServerHandle
export declare class ServerHandle {
  stop(): void
  on(event: string, cb: (...args: any[]) => any): void
}
